bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # URL pattern for viewing the bag.
    # This pattern matches the root URL of the bag app
    # and maps it to the view_bag view.
    # 'view_bag' can be used to refer to this URL in templates and views.
    path("", views.view_bag, name="view_bag"),
    # URL pattern for adding an item to the bag.
    # This pattern matches URLs of the form "add/<item_id>/"
    # where <item_id> is a placeholder for the ID of the item being added.
    # The item_id is passed as an argument to the add_to_bag view.
    # The name 'add_to_bag' can be used to refer to this URL pattern
    # in templates and views.
    path("add/<item_id>/", views.add_to_bag, name="add_to_bag"),
    path("remove/<item_id>/", views.remove_from_bag, name="remove_from_bag"),
]

board_gamers_vault/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler500, handler403, handler405

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("marketplace/", include("marketplace.urls")),
    path("bag/", include("bag.urls")),
    path("checkout/", include("checkout.urls")),
    path("profiles/", include("profiles.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Handling custom error pages
handler404 = "board_gamers_vault.views.handler404"
handler500 = "board_gamers_vault.views.handler500"
handler403 = "board_gamers_vault.views.handler403"
handler405 = "board_gamers_vault.views.handler405"

marketplace/urls.py
from django.urls import path, include
from . import views

# URL pattern for listing games
urlpatterns = [
    path("", views.games_list, name="games_list"),
    path("<int:game_id>/", views.game_detail, name="game_detail"),
    path("add/", views.add_game, name="add_game"),
    path("edit/<int:game_id>/", views.edit_game, name="edit_game"),
    path("delete/<int:game_id>/", views.delete_game, name="delete_game"),
]

marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string

# Create your models here.


class Category(models.Model):
    """
    Model representing a game category.

    Attributes:
        CATEGORY_CHOICES (list): List of tuples containing category
        identifiers and human-readable names.
        name (CharField): Name of the category, chosen from CATEGORY_CHOICES.
    """

    CATEGORY_CHOICES = [
        ("role_playing", "Role-playing"),
        ("cooperatives", "Cooperatives"),
        ("bluffing", "Bluffing"),
        ("area_control", "Area control"),
        ("placement", "Placement"),
        ("memory", "Memory"),
        ("miniatures", "Miniatures"),
        ("war_games", "War games"),
        ("worker_placement", "Worker placement"),
        ("strategy", "Strategy"),
        ("deck_building", "Deck Building"),
        ("city_building", "City Building"),
        ("party_games", "Party Games"),
        ("storytelling", "Storytelling"),
    ]

    class Meta:
        verbose_name_plural = "Categories"

    name = models.CharField(
        max_length=100, choices=CATEGORY_CHOICES, unique=True
        )

    def __str__(self):
        return self.get_name_display()  # Display the human-readable value


class Game(models.Model):
    """
    Model representing a game.

    Attributes:
        CONDITION_CHOICES (list): List of tuples containing condition
        identifiers and human-readable names.
        sku (CharField): Unique SKU for the game.
        title (CharField): Title of the game.
        price (DecimalField): Price of the game.
        is_available (BooleanField): Availability status of the game.
        condition (CharField): Condition of the game,
        chosen from CONDITION_CHOICES.
        category (ForeignKey): Category of the game,
        linked to the Category model.
        image (ImageField): Image of the game.
        image_url (URLField): URL of the game's image.
        seller (ForeignKey): Seller of the game, linked to the User model.
        description (TextField): Description of the game.
        seller_comment (TextField): Additional comments from the seller.
    """
    CONDITION_CHOICES = [
        ("as_new", "As new"),
        ("great", "Great"),
        ("good", "Good"),
        ("fair", "Fair"),
        ("signs_of_time", "Signs of time"),
        ("heavily_used", "Heavily used"),
    ]

    sku = models.CharField(max_length=40, unique=True, blank=True)
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)
    condition = models.CharField(max_length=15, choices=CONDITION_CHOICES)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, related_name="games"
    )
    image = models.ImageField(upload_to="game_images/", blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    seller = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="games")
    description = models.TextField()
    seller_comment = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.sku:
            self.sku = self.generate_sku()
        super(Game, self).save(*args, **kwargs)

    def generate_sku(self):
        return get_random_string(length=40)

    def __str__(self):
        return self.title

    @property
    def availability_status(self):
        """
        Property to get the availability status of the game.

        Returns:
            str: 'Available' if the game is available,
            otherwise 'Not Available'.
        """
        return "Available" if self.is_available else "Not Available"

    def mark_as_purchased(self):
        """
        Mark the game as purchased by setting its availability to False.
        """
        self.is_available = False
        self.save()


class SellerProfile(models.Model):
    """
    Model representing a seller's profile.

    Attributes:
        user (OneToOneField): User associated with the seller profile.
        standard_delivery_fee (DecimalField):
        Standard delivery fee charged by the seller.
        free_delivery_threshold (DecimalField):
        Purchase amount threshold for free delivery.
    """
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="seller_profile"
    )
    standard_delivery_fee = models.DecimalField(
        max_digits=10, decimal_places=2, default=5.00
    )
    free_delivery_threshold = models.DecimalField(
        max_digits=10, decimal_places=2, default=50.00
    )

    def __str__(self):
        return self.user.username

marketplace/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Game, Category


class GameForm(forms.ModelForm):
    """
    Form for creating and updating Game instances.
    """

    class Meta:
        model = Game
        # fields = "__all__"  # Use all fields from the Game model
        exclude = ["seller"]

    image = forms.ImageField(
        label="Image", required=False, widget=CustomClearableFileInput
    )

    def __init__(self, *args, **kwargs):
        """
        Initialize the form and dynamically populate category choices.
        Add CSS classes to form fields for consistent styling.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        super().__init__(*args, **kwargs)

        # Retrieve all categories from the database
        categories = Category.objects.all()

        # Create a list of tuples with category id and name
        name = [(c.id, c.name) for c in categories]

        # Set the category field choices to the retrieved categories
        self.fields["category"].choices = name

        self.fields["price"].label = "Price (£)"

        # Add CSS classes to form fields for styling
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "border-black rounded-0"

marketplace/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Game, Category
from .forms import GameForm

# Create your views here.


def games_list(request):
    """A view to show all products, including sorting and search queries"""
    games = Game.objects.filter(is_available=True)
    # Fetch all games from the database
    # 'games' is the name of the variable that holds
    # the data you retrieve from the database
    # in your view function
    query = None
    categories = None
    conditions = None
    sort = None
    direction = None
    no_games_message = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'title':
                sortkey = 'lower_title'
                games = games.annotate(lower_title=Lower('title'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f"-{sortkey}"
            games = games.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            games = games.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

            if not games.exists():
                no_games_message = "No games found for the selected category."

        if 'condition' in request.GET:
            conditions = request.GET['condition'].split(',')
            games = games.filter(condition__in=conditions)

            if not games.exists():
                no_games_message = "No games found for the selected condition."

        if "q" in request.GET:
            query = request.GET["q"]
            if not query:
                messages.error(request, "Please enter a search criteria.")
                return redirect(reverse("games_list"))

            queries = (
                Q(title__icontains=query) |
                Q(description__icontains=query)
            )
            # i makes the case insensitive
            games = games.filter(queries)

    current_sorting = f"{sort}_{direction}"

    context = {
        "games_list": games,  # 'games_list' is the name of the key in the
        # dictionary (context) that you pass to the
        # template. The template uses this key
        "search_term": query,
        "current_categories": categories,
        "current_conditions": conditions,
        "current_sorting": current_sorting,
        "no_games_message": no_games_message,
    }
    return render(request, "marketplace/games_list.html", context)


def game_detail(request, game_id):
    """A view to show individual product details"""
    game = get_object_or_404(Game, id=game_id)  # primary key lookup
    context = {
        "game": game,
        "availability_status": game.availability_status,
    }
    return render(request, "marketplace/game_detail.html", context)


@login_required
def add_game(request):
    """Add a product to the store"""
    if request.method == 'POST':
        form = GameForm(request.POST, request.FILES)
        if form.is_valid():
            game = form.save(commit=False)  # Save the form data to a variable
            game.seller = request.user
            game.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('game_detail', args=[game.id]))
        else:
            messages.error(request, 'Failed to add product. '
                                    'Please ensure the form is valid.')
    else:
        form = GameForm()

    template = "marketplace/add_game.html"
    context = {
        "form": form,
    }

    return render(request, template, context)


@login_required
def edit_game(request, game_id):
    """Edit a product"""

    # Retrieve the game object
    game = get_object_or_404(Game, pk=game_id)

    # Check if the logged-in user is the seller of the game
    if game.seller != request.user:
        messages.error(request, "Sorry, only the seller edit this game.")
        return redirect(reverse("home"))

    if request.method == "POST":
        form = GameForm(request.POST, request.FILES, instance=game)
        if form.is_valid():
            game = form.save()
            messages.success(request, "Product successfully updated!")
            return redirect(reverse("game_detail", args=[game.id]))
    # If form is invalid, continue to render the form with error messages
    else:
        form = GameForm(instance=game)
        messages.info(request, f"You are editing {game.title}")

    # This else block ensures that when the form is invalid during editing,
    # the error message is set correctly
    if not form.is_valid() and request.method == "POST":
        messages.error(
            request, "Failed to update game. Please ensure the form is valid."
        )

    template = "marketplace/edit_game.html"
    context = {
        "form": form,
        "game": game,
    }

    return render(request, template, context)


@login_required
def delete_game(request, game_id):
    """ Delete a product from the store """
    game = get_object_or_404(Game, pk=game_id)

    if game.seller != request.user:
        messages.error(request, "Sorry, only game owners "
                                "can do that.")
        return redirect(reverse("home"))

    game.delete()
    messages.success(request, 'Game deleted!')
    return redirect(reverse('games_list'))

marketplace/templates/marketplace/add_game.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row management">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4 logo-font-management">Boardgames Management</h2>
            <h5 class="text-muted">Add a game to sell</h5>
            <h7 class="text-muted">Please make sure to include delivery costs in the product price</h7>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'add_game' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- <p class="card-text">{{ form.sku | as_crispy_field }}</p> -->
                <p class="card-text">{{ form.title | as_crispy_field }}</p>
                <p class="card-text">{{ form.price | as_crispy_field }}</p>
                <p class="text-muted">Leave this box ticked if your game is available:</p>
                <p class="card-text">{{ form.is_available | as_crispy_field }}</p>
                <p class="card-text">{{ form.condition | as_crispy_field }}</p>
                <p class="card-text">{{ form.category | as_crispy_field }}</p>
                <p class="card-text">{{ form.description | as_crispy_field }}</p>
                <p class="card-text">{{ form.seller_comment | as_crispy_field }}</p>
                <p class="card-text">{{ form.image | as_crispy_field }}</p>
                <!-- To check for errors -->
                {% if form.errors %}
                {{ form.errors }}
                {% endif %}
                <div class="text-center mb-5">
                    <a class="btn btn-outline-black" href="{% url 'games_list' %}">Cancel</a>
                    <button class="btn btn-black" type="submit">Add Game</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

marketplace/templates/marketplace/game_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
    <div id="gamelist-detail" class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2 mt-4">
                <div class="image-container mx-auto my-5">
                    {% if game.image %}
                    <a href="{{ game.image.url }}" target="_blank">
                        <img class="card-img-top img-fluid" src="{{ game.image.url }}" alt="{{ game.title }}">
                    </a>
                    {% else %}
                    <a href="#">
                        <img class="card-img-top img-fluid" src="/media/no-image-placeholder.png" alt="{{ game.title }}">
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-4 mt-md-5">
                    <p class="mb-0 fs-2 font-weight-bold game-title">{{ game.title }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">£{{ game.price }}</p>
                    {% if game.category %}
                    <p class="small listing mt-1 mb-0">
                        <a class="text-muted" href="{% url 'games_list' %}?category={{ game.category.name }}">
                            <small class="text-muted game-category"><i class="fas fa-play"></i> {{ game.category }}</small>
                        </a>
                        <p class="mb-0 text-left"><span class="details-list">Condition:</span> {{ game.get_condition_display }}</p>
                    </p>
                    {% endif %}

                    <p class="mb-0 text-left"><span class="details-list">Seller:</span> {{ game.seller }}</p>
                    <p class="mt-3"><span class="details-list">Description:</span> {{ game.description|safe }}</p>
                    <p class="mt-3"><span class="details-list">What the seller says:</span> {{ game.seller_comment|safe }}</p>
                    {% if game.seller == request.user %}
                    <small class="ml-3">
                        <a href="{% url 'edit_game' game.id %}">Edit</a> |
                        <a class="text-danger" href="{% url 'delete_game' game.id %}">Delete</a>
                    </small>
                    {% endif %}
                    <!-- Form to add a product to the shopping bag -->
                    <form class="form" action="{% url 'add_to_bag' game.id %}" method="POST">
                        <!-- Django template tag to include the CSRF token for security -->
                        {% csrf_token %}
                        <input type="hidden" name="redirect_url" value="/custom/redirect/url/" />
                            <div class="col-12">
                                <!-- Link to go back to the products page -->
                                <a href="{% url 'games_list' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <!-- Icon for the button -->
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <!-- Submit button to add the product to the bag -->
                                <input type="submit" class="btn btn-black text-uppercase mt-5" value="Add to Bag">
                            </div>
                            <!-- Hidden input to store the current page URL for redirection after form submission -->
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

marketplace/templates/marketplace/games_list.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div id="gamelist-container" class="container-fluid">
    <div class="row">
        <div class="col text-center mt-4">
            <h2 class="logo-font logo-on-sale">Board Games on sale</h2>
                {% for c in current_categories %}
                    <a class="category-badge text-decoration-none" href="{% url 'games_list' %}?category={{ c.name }}">
                        <span class="p-2 mt-2 badge badge-white text-black rounded-0 border border-dark">{{ c.get_name_display }}</span>
                    </a>
                {% endfor %}
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        {% if no_games_message %}
        <div class="alert alert-warning" role="alert">
            {{ no_games_message }}
        </div>
        {% endif %}
        <div class="product-container col-10">
            <div class="row mt-1 mb-2">
                <div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-md-end">
                    <div class="sort-select-wrapper w-50">
                        <select id="sort-selector" class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                            <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                            <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)
                            </option>
                            <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)
                            </option>
                            <option value="condition_asc" {% if current_sorting == 'condition_asc' %}selected{% endif %}>Condition (as new to poor)
                            </option>
                            <option value="condition_desc" {% if current_sorting == 'condition_desc' %}selected{% endif %}>Condition (poor to as new)
                            </option>
                            <option value="title_asc" {% if current_sorting == 'title_asc' %}selected{% endif %}>Name (A-Z)</option>
                            <option value="title_desc" {% if current_sorting == 'title_desc' %}selected{% endif %}>Name (Z-A)</option>
                            <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category (A-Z)
                            </option>
                            <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category (Z-A)
                            </option>
                        </select>
                    </div>
                </div>
                    <div class="col-12 col-md-6 order-md-first">
                        <p class="text-muted mt-3 text-center text-md-left">
                            {% if search_term or current_categories or current_sorting != 'None_None' %}
                            <span class="small"><a href="{% url 'games_list' %}">All items </a> | </span>
                            {% endif %}
                            {{ games_list|length }} Games{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                        </p>
                    </div>
            </div>
            <div class="row py-4">
                {% for game in games_list %}
                <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                    <div class="card h-100 border-0">
                        {% if game.image %}
                        <a href="{% url 'game_detail' game.id %}">
                            <img class="card-img-top img-fluid" src="{{ game.image.url }}" alt="{{ game.title }}">
                        </a>
                        {% else %}
                        <a href="{% url 'game_detail' game.id %}">
                            <img class="card-img-top img-fluid" src="/media/no-image-placeholder.png" alt="{{ game.title }}">
                        </a>
                        {% endif %}
                        <div class="card-body pb-0">
                            <p class="lead mb-0 text-left">{{ game.title }}</p>
                        </div>
                        <div class="card-footer bg-white pt-0 border-0 text-left">
                            <div class="row">
                                <div class="col">
                                    <p class="lead mb-0 text-left font-weight-bold">£{{ game.price }}</p>
                                    <!-- Check availability -->
                                    <p class="{% if game.is_available %}text-success{% else %}text-danger{% endif %}">
                                    {{ game.availability_status }}
                                    </p>
                                    {% if game.is_available %}
                                    <a href="{% url 'game_detail' game.id %}">
                                    <button>Details</button>
                                    </a>
                                    {% else %}
                                    <button disabled>Not Available</button>
                                    {% endif %}
                                    {% if game.category %}
                                    <p class="small mt-1 mb-0">
                                        <a class="text-muted"
                                            href="{% url 'games_list' %}?category={{ game.category.name }}">
                                            <small class="text-muted"><i class="fas fa-play"></i> {{ game.category }}</small>
                                        </a>
                                    </p>
                                    {% endif %}
                                    <p class="mb-0 text-left">Condition: {{ game.get_condition_display }}</p>
                                    <p class="mb-0 text-left">Seller: {{ game.seller }}</p>
                                    <!-- Edit and delete functionality -->
                                    {% if game.seller == request.user %}
                                    <small class="ml-3">
                                        <a href="{% url 'edit_game' game.id %}">Edit</a> |
                                        <a class="text-danger" href="{% url 'delete_game' game.id %}">Delete</a>
                                    </small>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:1 %}
                <div class="col-12 d-sm-none mb-5">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:2 %}
                <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:3 %}
                <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:4 %}
                <div class="col-12 d-none d-xl-block mb-5">
                    <hr>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="btt-button shadow-sm rounded-0 border border-black">
    <a class="btt-link bg-white d-flex  h-100">
        <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
    </a>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}

<!-- Script to handle 'back to top' link functionality -->
<script type="text/javascript">
    $('.btt-link').click(function (e) {
        window.scrollTo(0, 0) // Scrolls the window to the top when the element with class 'btt-link' is clicked
    })
</script>

<!-- Script to handle sorting functionality -->
<script type="text/javascript">
    // Event listener for changes on the sort selector
    $('#sort-selector').change(function () {
        var selector = $(this); // The jQuery object for the sort selector
        var currentUrl = new URL(window.location); // Get the current URL

        var selectedVal = selector.val(); // Get the selected value from the sort selector
        if (selectedVal != "reset") { // If the selected value is not "reset"
            var sort = selectedVal.split("_")[0]; // Extract the sort field from the selected value
            var direction = selectedVal.split("_")[1]; // Extract the sort direction from the selected value
            
            // Update the URL with the selected sort field and direction
            currentUrl.searchParams.set("sort", sort);
            currentUrl.searchParams.set("direction", direction);

            window.location.replace(currentUrl); // Reload the page with the updated URL
        } else { // If the selected value is "reset"
            // Remove the sort and direction parameters from the URL
            currentUrl.searchParams.delete("sort");
            currentUrl.searchParams.delete("direction");

            window.location.replace(currentUrl); // Reload the page with the updated URL
        }
    })
</script>
{% endblock %}